version: '1.0'
services:
  mysqldb:
    image: mysql:latest
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=hung11pp
      - MYSQL_DATABASE=student
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build:
      context: .
      target: development
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true",
      "spring.datasource.username" : "$MYSQLDB_USER",
      "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
      "spring.jpa.hibernate.ddl-auto" : "update"
    }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: